# Arrays

- ## *1-D Array*

In [1]:
import numpy as np
arr = np.array([4,4,4,4])
arr

array([4, 4, 4, 4])

In [31]:
import numpy as np
arr = np.array(["first","second","third","fourth"])
arr

array(['first', 'second', 'third', 'fourth'], dtype='<U6')

In [5]:
import numpy as np
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [6]:
import numpy as np
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [7]:
import numpy as np
arr = np.empty(4)
arr

array([1., 1., 1., 1.])

In [10]:
import numpy as np
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [12]:
import numpy as np
arr = np.arange(4,14)
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [14]:
import numpy as np
arr = np.arange(4,14,2)
arr

array([ 4,  6,  8, 10, 12])

In [26]:
import numpy as np
arr = np.linspace(0,10,num=4)
arr

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [18]:
import numpy as np
arr = np.ones(4,dtype=np.int8)
arr

array([1, 1, 1, 1], dtype=int8)

- ## *2-D Array*

In [21]:
import numpy as np
arr = np.array([[4,4,4,4],
                [4,4,4,4]])
arr

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [22]:
import numpy as np
arr = np.zeros([4,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
import numpy as np
arr = np.ones([4,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
import numpy as np
arr = np.empty([4,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- ## *3-D Array*

In [27]:
import numpy as np
arr = np.array([[[4,4,4,4],
                [4,4,4,4]],
                [[4,4,4,4],
                [4,4,4,4]]
               ])
arr

array([[[4, 4, 4, 4],
        [4, 4, 4, 4]],

       [[4, 4, 4, 4],
        [4, 4, 4, 4]]])

In [28]:
import numpy as np
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Array Functions

- ## *Sort*

In [33]:
import numpy as np
arr = np.array([5,34,25,26,274,0.3,45.3])
arr.sort()
arr

array([  0.3,   5. ,  25. ,  26. ,  34. ,  45.3, 274. ])

- ## *Max*

In [37]:
import numpy as np
arr = np.array([5,34,25,26,274,0.3,45.3])
arr.max()

274.0

- ## *Min*

In [38]:
import numpy as np
arr = np.array([5,34,25,26,274,0.3,45.3])
arr.min()

0.3

- ## *Concatenate*

In [52]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [53]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [54]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

- ## *Dimensions*

In [56]:
import numpy as np
arr = np.array([[1,2],[3,4]])
arr.ndim

2

- ## *Size*

In [57]:
import numpy as np
arr = np.array([[1,2],[3,4]])
arr.size

4

- ## *Shape*

In [58]:
import numpy as np
arr = np.array([[1,2],[3,4]])
arr.shape

(2, 2)

- ## *Reshape*

In [59]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- ## *Converting 1-D Into 2-D Array*

In [62]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[np.newaxis,:]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [63]:
arr[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

- ## *Slicing*

In [64]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[3:6]

array([4, 5, 6])

- ## *Multiplying*

In [66]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr*4

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36])

- ## *Addition*

In [67]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr+4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

- ## *Sum*

In [68]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.sum()

45

- ## *Mean*

In [69]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.mean()

5.0